/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isbn.grafico;

/**
 *
 * @author lsras
 */
public class ISBN extends javax.swing.JFrame {

    /**
     * Creates new form ISBN
     */
    public ISBN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Digite su codigo de ISBN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -20, 310, 150));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isbn/grafico/1200px-EAN-13-ISBN-13.svg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ISBN=new String();
        ISBN=this.jTextField1.getText();
        boolean Control= true;
    while(Control){
        Control=ValidarTamanos(ISBN);
        this.jLabel2.setText("Error");
    }
    if(ISBN.length()==10){
        Algoritmo10(ISBN);
    }
    else{
        Algoritmo13(ISBN);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    boolean ValidarNumeros(String ISBN , int Longitud){
    for(int c=0; c<Longitud; c++){
        if(ISBN.charAt(c)<48 || ISBN.charAt(c)>57){
            this.jLabel2.setText("Codigo ISBN erroneo, Por favor intentelo de nuevo\n");
            return true;
        }
    }
    return false;
}
    
boolean ValidarTamanos(String ISBN){
    if(ISBN.length()==10){
        if(ValidarNumeros(ISBN,9)){
            return true;
        }
        if(ISBN.charAt(9)=='x'||ISBN.charAt(9)=='X'){
            return false;
        }
        else{
            if(ISBN.charAt(9)<48 || ISBN.charAt(9)>57){
                this.jLabel2.setText("Codigo ISBN erroneo, Por favor intentelo de nuevo\n");
                return true; 
            }
        }
        return false;
    }
    if(ISBN.length()==13){
        if(ValidarNumeros(ISBN,13)){
            return true;
        }
        return false;
    }
    else{
        this.jLabel2.setText("Codigo ISBN erroneo, Por favor intentelo de nuevo\n");
        return true;
    }
}

void Algoritmo10(String ISBN){
    int m =10;
    int suma=0;
    if(ISBN.charAt(9)=='X'||ISBN.charAt(9)=='x'){
        for(int c=0; c<9 ;c++){
            suma += ((int)(ISBN.charAt(c))-48)*m; 
            m--;
        }
        suma += 10*m;
    }
    else{
        for(int c=0; c<10 ;c++){
            suma += ((int)(ISBN.charAt(c))-48)*m; 
            m--;
        }
    }
    if(suma % 11==0){
        this.jLabel2.setText("Su codigo ISBN es correcto!!! :)");
    }
    else{
        this.jLabel2.setText("Su codigo ISBN es incorrecto :(");
    }
}

void Algoritmo13(String ISBN){
    int SumaFinal = 0;
    int SumaPar = 0;
    int SumaImpar = 0;
    for(int c = 0; c<13; c++){
        if(c%2==0){
            SumaImpar+=((int)ISBN.charAt(c))-48;
        }
        else{
            SumaPar+=((int)ISBN.charAt(c))-48;
        }
    }
    SumaFinal = SumaImpar+SumaPar*3;
    if(SumaFinal%10==0){
        this.jLabel2.setText("Su codigo ISBN es correcto!!! :)");
    }
    else{
        this.jLabel2.setText("Su codigo ISBN es incorrecto :(");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISBN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
